version: '3.10'

services:
  web:
    build: ./backend
    command: uvicorn core.config:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/:/usr/src/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  db:
    build:
      context: ./db
    restart: always
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
